### ISSUE TITLE
Apply themes to Location Geometry.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#203] opened 2019-11-26 12:20 UTC
The value for a location's geometry entry maybe a feature collection returned as geojson from a complex lookup defined as a fieldfx.

It should be possible to assign a theme with the same format as provided in layer styles to the feature collection. The theme should be in the style definition which is already part of the geometry entry definition.

**Comment by cityremade** [comment] 2020-01-29 13:18
I am closing it as duplicate of #151

**Closed by cityremade** 2020-01-29 13:18 UTC
Labels: Feature
