### ISSUE TITLE
Zoom hooks

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#45] opened 2018-12-04 12:05 UTC
The zoom hooks doesn't seem to initiate at the moment.

**Comment by RobAndrewHurst** [comment] 2018-12-04 12:05
The zoom hooks doesn't seem to initiate at the moment.

**Comment by dbauszus-glx** [comment] 2018-12-06 12:09
This was caused by a change of location not applying the map view change event listeners for hooks.

Fixed now.

**Closed by dbauszus-glx** 2018-12-06 12:09 UTC
Labels: bug
