### ISSUE TITLE
Confirm Dialog: Text wrapping 

### ISSUE THREAD

**Issue by AlexanderGeere** [GEOLYTIX/xyz#1553] opened 2024-10-10 13:28 UTC
## Description

The confirm dialog should wrap text on its default width to avoid: 
![Screenshot 2024-10-10 151444](https://github.com/user-attachments/assets/85dbd6ac-a4d2-477a-9cc5-9f60d2956313)

If you create a confirm dialog with very long text it will scroll vertically. 

## Type of Issue 
- ✅ Bug

**Comment by cityremade** [comment] 2024-10-10 15:51
Is it in a plugin with additional/missing css?
this is what I am getting within confirm dialog when I paste something very long:
<img width="432" alt="Screenshot 2024-10-10 at 16 48 59" src="https://github.com/user-attachments/assets/f9b06f3f-c190-44a1-a26e-c9c0fc02ca1f">

**Comment by AlexanderGeere** [comment] 2024-10-11 09:35
I use firefox, might be a browser difference.

**Comment by dbauszus-glx** [comment] 2024-10-21 16:28
Closed as unable to reproduce.

**Closed by dbauszus-glx** 2024-10-21 16:28 UTC
Labels: UI
